version: "3"
services:
  #=================================
  # AUTH SERVICES ENVIRONMENT
  #=================================
  auth:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: educational_kc
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database/postgres
      - KC_DB_USERNAME=admin123
      - KC_DB_PASSWORD=admin123
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - go_networks
  #=================================
  # DATABASE SERVICES ENVIRONMENT
  #=================================
  database:
    image: postgres:14-alpine
    container_name: educational_kc_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin123
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - go_networks
  #=================================
  # VOLUME PERSISTENT DATA
  #=================================
volumes:
  database:
  #=================================
  # NETWORK SHARING GROUP
  #=================================
networks:
  go_networks:

