version: "3.9"
services:
    db:
        image: mysql
        container_name: blablacar_db
        ports:
            - 3310:3306
        restart: unless-stopped
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: blablacar
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - ./db_data:/var/lib/mysql
